---
title: "NYC Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse) 
library(p8105.datasets)
library(plotly)
#Load and Tidy data
data("rest_inspec")

rest_inspec =
  rest_inspec %>%
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  mutate(boro = str_to_title(boro))

```

Column {.sidebar}
-----------------------------------------------------------------------
**Figure 1.** 
Most of the data are collected from October 2013 to October 2017. The higher the scores the Cafe obtained, the lower the grade it earned.The cutoff score for A is lower than 13, and for B is around 28. However, there are also some exceptions with low score and grade C.

**Figure 2.**
The number of Cafe in A, B, C grade in vaious boroughs in NYC.

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Cc][Aa][Ff][Ee]"))  %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  spread(key = grade, value = n) %>% 
  arrange(desc(A)) %>% 
  knitr::kable()
```

Manhattan has the largest number of Cafe with grade A.

**Figure 3 .**
The scores for C vary a lot in Manhattan and Queens.
  
Column {data-width=550}
-----------------------------------------------------------------------

### Figure 1. The score of Cafe with A, B, C grade on specific inspection date

```{r}
rest_inspec %>%  
  mutate(text_label = str_c("Resturant: ", dba, 
                            "\nGrade: ", grade, 
                            '\nScores: ', score)) %>% 
  filter(str_detect(dba, "[Cc][Aa][Ff][Ee]")) %>%
  plot_ly(x  = ~inspection_date, y = ~score, type = "scatter", mode = "markers",
          text = ~text_label, color = ~grade) %>%
  layout(xaxis = list(title ="Inspection date"), yaxis = list(title = "Score"))

```



Column {data-width=450}
-----------------------------------------------------------------------

### Figure 2. The number of Cafe in A, B, C grade in vaious boroughs in NYC

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Cc][Aa][Ff][Ee]")) %>%
  mutate(boro = fct_infreq(boro)) %>% 
  plot_ly(x  = ~boro, type = "histogram", color = ~grade) %>%
  layout(xaxis = list(title ="Borough"), yaxis = list(title = "Count"))
```

### Figure 3. The score of Cafe with A, B, C grade in vaious boroughs in NYC

```{r}
rest_inspec %>% 
  mutate(text_label = str_c("Resturant: ", dba, 
                            "\nGrade: ", grade, 
                            '\nScores: ', score)) %>% 
  filter(str_detect(dba, "[Cc][Aa][Ff][Ee]")) %>%
  plot_ly(x  = ~boro, y = ~score, type = "box",
          text = ~text_label, color = ~grade) %>%
  layout(xaxis = list(title ="Borough"), yaxis = list(title = "Score"))

```

